
# Post http://localhost:3000/users/signup
post https://todo-app-backend-h8w0.onrender.com/users/signup
Content-Type: application/json

{
    "fullNames":"Mofori",
    "email":"mofori@gmail.com",
    "password":"123456"
}


###

Post https://todo-app-backend-h8w0.onrender.com/users/login
Content-Type: application/json

{ 
    "email":"hakeemsmith@gmail.com",

    "password":"123456"
}



###

Get https://todo-app-backend-h8w0.onrender.com/users/

###

Post https://todo-app-backend-h8w0.onrender.com/notes/
Content-Type: application/json

{
    "title":"Fixing Bugs",
    "details":"The bug of fetching all notes has being fixed",
    "id":"2",
    "owner":"67978a71dd90b3610282aa27"
}

###
GET  https://todo-app-backend-h8w0.onrender.com/notes



###

Put http://localhost:3000/users/update
Content-Type: application/json

{
    "id":"674cc8d74a4763a3e172b939",
    "fullNames":"Hakeem"
}
###
DELETE  https://todo-app-backend-h8w0.onrender.com/users/672ed22d205a4f1f8f3a75e5



###
Post http://localhost:3000/notes/
Content-Type: application/json

{
    'title': 'Texting',
    'body': 'this message meets you well',
    'id':  '337',
}


###
Put http://localhost:3000/users/update
Content-Type: application/json

{
    "fullNames":"Testing"
}

###
# Get mongodb+srv://BetrandCliff:<db_password>@cluster0.akktj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0