
Post http://localhost:3000/users/signup
# post https://todo-app-backend-h8w0.onrender.com/users/signup
Content-Type: application/json

{
    "fullNames":"Mofori",
    "email":"mofori@gmail.com",
    "password":"123456"
}


###

Post https://localhost:3000/users/login
Content-Type: application/json

{ 
    "email":"betrandcliff@gmail.com",

    "password":"12345678"
}

###
# Get https://todo-app-backend-m1js.onrender.com/users

###

Get http://localhost:3000/record/


###
DELETE http://localhost:3000/record/687e27568565a4f2f123d8c9

###

Get http://localhost:3000/users/otps
###

Post http://localhost:3000/notes/
Content-Type: application/json

{
    "createdby":"67feadb4b11216b645e0cdb2"
}

###
GET  http://localhost:3000/users/

###
GET  http://localhost:3000/notes/

###
DELETE  http://localhost:3000/notes/68ef5910db6a8a85484a1326


###
Post  https://todo-app-backend-m1js.onrender.com/users/verification
Content-Type: application/json

{
    "fullNames":"Lois",
    "email":"loisbania0@gmail.com",
    "password":"12345678"
}

###

Put http://localhost:3000/users/update
Content-Type: application/json

{
    "id":"674cc8d74a4763a3e172b939",
    "fullNames":"Hakeem"
}
###
DELETE  https://todo-app-backend-m1js.onrender.com/users/6884562523c6bd9530f47f87 


###
curl -X POST https://todo-app-backend-m1js.onrender.com/users/login -H "Content-Type: application/json" -d '{"email":"betrandcliff@gmail.com","password":"12345678"}'


###
Put http://localhost:3000/users/update
Content-Type: application/json

{
    "fullNames":"Testing"
}

###
# Get mongodb+srv://BetrandCliff:<db_password>@cluster0.akktj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0