
Post http://localhost:3000/users/signup
# post https://todo-app-backend-h8w0.onrender.com/users/signup
Content-Type: application/json

{
    "fullNames":"Mofori",
    "email":"mofori@gmail.com",
    "password":"123456"
}


###

Post https://localhost:3000/users/login
Content-Type: application/json

{ 
    "email":"sakwecliff@gmail.com",

    "password":"12345678"
}



###

Get http://localhost:3000/record/


###

Get http://localhost:3000/users/otps
###

Post https://todo-app-backend-h8w0.onrender.com/notes/
Content-Type: application/json

{
    "title":"Visiting mum today",
    "details":"The bug of fetching all notes has being fixed",
    "id":"23",
    "createdby":"67feadb4b11216b645e0cdb2"
}

###
GET  http://localhost:3000/notes/6877854e75d35ddb1a9c3a39


###
GET  http://localhost:3000/notes/general/


###

Put http://localhost:3000/users/update
Content-Type: application/json

{
    "id":"674cc8d74a4763a3e172b939",
    "fullNames":"Hakeem"
}
###
DELETE  https://todo-app-backend-h8w0.onrender.com/users/672ed22d205a4f1f8f3a75e5



###
Post http://localhost:3000/notes/
Content-Type: application/json

{
    'title': 'Texting',
    'body': 'this message meets you well',
    'id':  '337',
}


###
Put http://localhost:3000/users/update
Content-Type: application/json

{
    "fullNames":"Testing"
}

###
# Get mongodb+srv://BetrandCliff:<db_password>@cluster0.akktj.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0