# render.yaml - Example configuration for Render
services:
  - name: my-web-service
    type: web
    env: node # Can be node, python, ruby, php, etc., depending on your stack
    region: oregon # Change to your preferred region
    buildCommand: npm install && npm run build # Adjust according to your build process
    startCommand: npm start # Adjust according to your start script
    plan: free # Change to starter/pro depending on your needs
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_KEY
        sync: true # If you're using Render Secrets

databases:
  - name: my-database
    type: postgresql
    plan: free # Change based on your requirements
    region: oregon
    user: postgres
    databaseName: my_database_name

staticSites:
  - name: my-static-site
    buildCommand: npm run build # Adjust for your static site generator (e.g., Next.js, Gatsby)
    publishPath: build # Adjust based on your build output directory
    region: oregon

# Uncomment and customize the following block if you have a cron job
# cronJobs:
#   - name: daily-job
#     schedule: '@daily'
#     command: npm run daily-task
#     plan: free
#     region: oregon
